# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/smartcar.xdc

# Block Designs: bd/smartcar/smartcar.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar || ORIG_REF_NAME==smartcar}]

# IP: bd/smartcar/ip/smartcar_processing_system7_0_0/smartcar_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_processing_system7_0_0 || ORIG_REF_NAME==smartcar_processing_system7_0_0}]

# IP: bd/smartcar/ip/smartcar_mygpio_ip_0_0/smartcar_mygpio_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_mygpio_ip_0_0 || ORIG_REF_NAME==smartcar_mygpio_ip_0_0}]

# IP: bd/smartcar/ip/smartcar_pwm_ip_0_0/smartcar_pwm_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_pwm_ip_0_0 || ORIG_REF_NAME==smartcar_pwm_ip_0_0}]

# IP: bd/smartcar/ip/smartcar_sr04_ip_0_0/smartcar_sr04_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_sr04_ip_0_0 || ORIG_REF_NAME==smartcar_sr04_ip_0_0}]

# IP: bd/smartcar/ip/smartcar_ps7_0_axi_periph_0/smartcar_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_ps7_0_axi_periph_0 || ORIG_REF_NAME==smartcar_ps7_0_axi_periph_0}]

# IP: bd/smartcar/ip/smartcar_rst_ps7_0_100M_0/smartcar_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_rst_ps7_0_100M_0 || ORIG_REF_NAME==smartcar_rst_ps7_0_100M_0}]

# IP: bd/smartcar/ip/smartcar_xbar_0/smartcar_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_xbar_0 || ORIG_REF_NAME==smartcar_xbar_0}]

# IP: bd/smartcar/ip/smartcar_speedsensor_ip_0_0/smartcar_speedsensor_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_speedsensor_ip_0_0 || ORIG_REF_NAME==smartcar_speedsensor_ip_0_0}]

# IP: bd/smartcar/ip/smartcar_auto_pc_0/smartcar_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==smartcar_auto_pc_0 || ORIG_REF_NAME==smartcar_auto_pc_0}]

# XDC: bd/smartcar/smartcar_ooc.xdc
