# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/xproject/smartcar/smartcar.cache/wt [current_project]
set_property parent.project_path F:/xproject/smartcar/smartcar.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths f:/xproject/ip_repo [current_project]
set_property ip_output_repo f:/xproject/smartcar/smartcar.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib F:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/hdl/smartcar_wrapper.v
add_files F:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/smartcar.bd
set_property used_in_implementation false [get_files -all f:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/ip/smartcar_processing_system7_0_0/smartcar_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all f:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/ip/smartcar_rst_ps7_0_100M_0/smartcar_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/ip/smartcar_rst_ps7_0_100M_0/smartcar_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all f:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/ip/smartcar_rst_ps7_0_100M_0/smartcar_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/ip/smartcar_xbar_0/smartcar_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/ip/smartcar_auto_pc_0/smartcar_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/smartcar_ooc.xdc]
set_property is_locked true [get_files F:/xproject/smartcar/smartcar.srcs/sources_1/bd/smartcar/smartcar.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/xproject/smartcar/smartcar.srcs/constrs_1/new/smartcar.xdc
set_property used_in_implementation false [get_files F:/xproject/smartcar/smartcar.srcs/constrs_1/new/smartcar.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top smartcar_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef smartcar_wrapper.dcp

catch { report_utilization -file smartcar_wrapper_utilization_synth.rpt -pb smartcar_wrapper_utilization_synth.pb }
